// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication4.Models
{
    public partial class GetCourseReportResult
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public int? TeacherCount { get; set; }
        public int? StudentCount { get; set; }
        public double? AvgGrade { get; set; }
    }
}
